export const taxRegimeOptions = [
    "General de Ley Personas Morales",
    "Personas morales con fines no lucrativos",
    "Sueldos y salarios e ingresos asimilados a salarios",
    "Arrendamiento",
    "Régimen de enajenación o adquisición de bienes",
    "Demás ingresos",
    "Residentes en el extrangero sin establecimiento permanente en Mexico",
    "Ingresos por dividendos (socios y accionistas)",
    "Personas fisicas con actividades empresariales yprofesionales",
    "Ingresos por intereses",
    "Régimen de los ingresos por obtención de premios",
    "Sin obligaciones fiscales",
    "Sociedades cooperaivas de producción que optan por diferir sus ingresos",
    "Incorporación Fiscal",
    "Actividades agricolas, ganaderas, silvícolas y pesqueras",
    "Opcional para grupos de sociedades",
    "Coordinados",
    "Régimen simplificado de confianza",
    "Régimen de las actividades empresariales con ingresos a travéz de plataformas tecnológicas",
  ];