const FIREBASE_API_KEY = import.meta.env.FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = import.meta.env.FIREBASE_AUTH_DOMAIN;
const FIREBASE_PROJECT_ID = import.meta.env.FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = import.meta.env.FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID = import.meta.env
  .FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = import.meta.env.FIREBASE_APP_ID;

console.log('FIREBASE_API_KEY: ', FIREBASE_API_KEY);

export const envs = {
  //API_DOMAIN: 'http://localhost:3000',
  API_DOMAIN: 'https://api.lovelia.me',

  // Firebase credentials
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
};
